<template>
  <div class="container">
    <div class="list-view">
      <div class="input-layout">
        <label>Customer Code </label>
        <input
          v-model="customer.code"
          placeholder="Autogenerated Customer Code"
        />
      </div>
      <div class="input-layout">
        <label>Customer Name </label>
        <input v-model="customer.name" placeholder="Enter Customer Name" />
      </div>
      <div class="input-layout">
        <label>Address </label>
        <textarea v-model="customer.address" placeholder="Address"></textarea>
      </div>
      <div class="input-layout">
        <label>State </label>
        <select v-model="customer.state">
          <option disabled value="">Please select state</option>
          <option>Kerala</option>
          <option>Tamil Nadu</option>
        </select>
      </div>
      <div class="input-layout">
        <label>Contact Person</label>
        <input
          v-model="customer.contactperson"
          placeholder="Enter Contact Person Name"
        />
      </div>
      <div class="input-layout">
        <label>Designation</label>
        <input
          v-model="customer.desig"
          placeholder="Contact Person's Designation'"
        />
      </div>
      <div class="input-layout">
        <label>Contact Number 1</label>
        <input v-model.number="customer.cnum1" type="number" />
      </div>
      <div class="input-layout">
        <label>Contact Number 2</label>
        <input v-model.number="customer.cnum2" type="number" />
      </div>
      <div class="input-layout">
        <label>Email ID</label>
        <input v-model="customer.email" placeholder="Enter Email ID" />
      </div>
      <div class="input-layout">
        <label>GST Number</label>
        <input
          v-model="customer.gst"
          type="text"
          placeholder="Enter GST Number"
        />
      </div>
      <div class="input-layout">
        <label>Credit Terms </label>
        <select v-model="customer.creditterm">
          <option disabled value="">Please select the credit terms</option>
          <option>Immediate Payment</option>
          <option>7 days</option>
          <option>30 days</option>
          <option>60 days</option>
          <option>90 days</option>
        </select>
      </div>
      <div>
        <button @click="addCustomer()" class="button btnadd">
          Save Customer
        </button>
      </div>
    </div>
    <div id="search">
      <div class="searchsection">
        <input
          type="text"
          name="searchCustomercode"
          id="searchCustomercode"
          v-model="searchcode"
          @keyup="searchcustomerbyCode()"
          placeholder="Search by Code"
        />
        <i class="fas fa-search"></i>
        <!--p>Searching content : {{ searchcode }}</p-->

        <input
          type="text"
          name="searchcustomername"
          id="searchcustomername"
          v-model="searchname"
          @keyup="searchcustomerbyName()"
          placeholder="Search by Name"
        />
        <i class="fas fa-search"></i>
        <!--p>Searching content : {{ searchname }}</p-->
      </div>
    </div>
    <div class="displaysection">
      <div class="table">
        <table id="customerTable">
          <thead>
            <tr>
              <th max-width="2px">Customer Code</th>
              <th>Customer Name</th>
              <th>Customer Address</th>
              <th>State</th>
              <th>Contact Person</th>
              <th>Designation</th>
              <th>Contact Num1</th>
              <th>Contact Num2</th>
              <th>Email ID</th>
              <th>GST Number</th>
              <th>Credit Terms</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody class="viewlimit">
            <tr v-for="(customer, index) in rows" :key="index">
              <td max-width="2px">{{ customer.code }}</td>
              <td>{{ customer.name }}</td>
              <td>{{ customer.address }}</td>
              <td>{{ customer.state }}</td>
              <td>{{ customer.contactperson }}</td>
              <td>{{ customer.desig }}</td>
              <td>{{ customer.cnum1 }}</td>
              <td>{{ customer.cnum2 }}</td>
              <td>{{ customer.email }}</td>
              <td>{{ customer.gst }}</td>
              <td>{{ customer.creditterm }}</td>

              <td>
                <span @click="editCustomer(index)" class="iconbutton"
                  ><i class="fas fa-pencil-alt"></i
                ></span>

                <span @click="deleteCustomer(index)" class="iconbutton"
                  ><i class="fas fa-trash"></i
                ></span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>


<script>
export default {
  data() {
    return {
      customer: {},
      searchname: "",
      searchcode: "",

      initialdata: [
        {
          code: "CU001",
          name: "CDE Pvt Ltd",
          address: "Trivandrum",
          state: "Kerala",
          contactperson: "Mr.AIY",
          desig: "Manager",
          cnum1: "9876543219",
          cnum2: "0471224433",
          email: "abcmanager@gmail.com",
          gst: "GSTIN1234567890123456",
          creditterm: "Immediate Payment",
        },
        {
          code: "CU002",
          name: "FGH Pvt Ltd",
          address: "Neyyatinkara",
          state: "Tamil Nadu",
          contactperson: "Mr.KOC",
          desig: "Purchase Manager",
          cnum1: "8475859472",
          cnum2: "",
          email: "xyz@gmail.com",
          gst: "",
          creditterm: "30 days",
        },
      ],
      rows: this.initialdata,
    };
  },

  methods: {
    addCustomer() {
      this.rows.push(this.customer);
      this.customer = {};
      //this.rows[index] = JSON.parse(JSON.stringify(this.rows[index]));
    },

    editCustomer(index) {
      this.customer = JSON.parse(JSON.stringify(this.rows[index]));
      //this.Customer = this.rows[index];
    },

    deleteCustomer(index) {
      var delconfirmation = confirm("Are you sure to delete this Customer ?");
      if (delconfirmation) {
        this.rows.splice(index, 1);
      }
    },
    searchcustomerbyCode() {
      this.rows = this.initialdata.filter((customer) =>
        customer.code.toLowerCase().includes(this.searchcode.toLowerCase())
      );
    },
    searchcustomerbyName() {
      this.rows = this.initialdata.filter((customer) =>
        customer.name.toLowerCase().includes(this.searchname.toLowerCase())
      );
    },
  },
  created() {
    this.searchcustomerbyCode();
    this.searchcustomerbyName();
  },
};
</script>

<style scoped>
.container {
  position: relative;
  /* height: 100%; */
  width: 100%;
}
.list-view {
  display: grid;
  grid-template-columns: 1fr 1fr;
  /*background-color: tan;*/
  text-align: left;
  margin: 25px 20px 5px 20px;
  /* overflow-y: auto;
  overflow-x: auto; */
}
/* .gridbutton {
  display: grid;
  grid-template-columns: 4fr 1fr;
  margin: 20px 10px 5px 10px;
}
.gridbutton input,
.gridbutton button {
  height: 20px;
  font-size: 18px;
}
.gridbutton input {
  width: 300px;
}
.gridbutton button {
  width: auto;
  cursor: pointer;
} */

.button {
  height: 25px;
  width: auto;
  border-radius: 30px;
  text-transform: uppercase;
  border: 1px solid black;
  box-shadow: 2px 2px 2px black;
  font-size: 15px;
  font-weight: bold;
  cursor: pointer;
  margin: 8px 0 0 30%;
  /*margin-top: 25px;*/
}
.iconbutton {
  width: auto;
  height: auto;
  border: none;
  background-color: transparent;
  cursor: pointer;
  padding: 5px 5px;
  gap: 10px;
}
.iconbutton i:hover {
  color: blue;
  font-size: 14px;
}

/* .btnadd {
  margin-left: 25%;
} */

.input-layout {
  display: flex;
  align-items: center;
  flex-direction: row;
  padding: 3px;
  margin: 0px 60px;
}
.input-layout label {
  margin-right: auto;
  font-size: 15px;
}
.input-layout input,
.input-layout select {
  width: 250px;
  height: 25px;
  font-size: 13px;
  border: 1px solid black;
  border-radius: 3px;
  outline: none;
}

.input-layout select {
  width: 255px;
}

.input-layout textarea {
  width: 250px;
  height: 70px;
  font-size: 13px;
  border: 1px solid black;
  border-radius: 3px;
  outline: none;
  /* width: 250px;
  height: 70px;
  font-size: 18px;
  border: 2px solid black;
  margin-left: 40px; */
}
input[type="number"]::-webkit-outer-spin-button,
input[type="number"]::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
.displaysection {
  position: absolute;
  /*background-color: burlywood;*/
  margin: 10px;
  height: 90%;
  overflow-y: auto;
  /* overflow-x: auto; */
  /*position: relative;*/
}

.table {
  /*border-collapse: collapse;*/

  max-width: 75vw;

  border: 2px solid #44475c;
  margin: 5px 5px 5px 5px;
}
/* .headerposition {
   position: sticky; 
  position: sticky;
  top: 0;
  z-index: 10;
} */

.table th {
  /*text-transform: uppercase;*/
  text-align: center;
  background: #44475c;
  color: #fff;
  padding: 3px;
  min-width: 20px;
  font-size: 13px;
  /*position: fixed;*/
}

.table td {
  text-align: left;
  padding-left: 3px;
  border-right: 2px solid #7d82a8;
  word-wrap: break-word;
  /*max-width: 140px;*/
  width: auto;
  font-size: 12px;
}

/*.table td:last-child {
  border-right: none;
}*/
.table tbody tr:nth-child(2n) td {
  background: #d4d8f9;
}

.searchsection {
  display: grid;
  grid-template-columns: 1fr 0.1fr 1fr 0.1fr 5fr;
  margin: 15px 20px 0px;
}
.searchsection input,
.searchsection i {
  border-right-style: none;
  border-left-style: none;
  border-top-style: none;
  border-bottom-width: medium;
  border-bottom-color: black;
  outline: none;
}
.searchsection i {
  margin-right: 35px;
  background-color: black;
  color: white;
  padding: 3px;
}
</style>
