<template>
  <div class="list-view">
    <div class="input-layout">
      <label>Vendor Code </label>
      <input v-model="vcode" placeholder="Autogenerated Vendor Code" />
    </div>
    <div class="input-layout">
      <label>Vendor Name </label>
      <input v-model="vname" placeholder="Enter Vendor Name" />
    </div>
    <div class="input-layout">
      <label>Address </label>
      <textarea v-model="vaddress" placeholder="Address"></textarea>
    </div>
    <div class="input-layout">
      <label>State </label>
      <select v-model="vstate">
        <option disabled value="">Please select state</option>
        <option>Kerala</option>
        <option>Tamil Nadu</option>
      </select>
    </div>
    <div class="input-layout">
      <label>Contact Person</label>
      <input v-model="vcontactperson" placeholder="Enter Contact Person Name" />
    </div>
    <div class="input-layout">
      <label>Designation</label>
      <input v-model="vdesig" placeholder="Contact Person's Designation'" />
    </div>
    <div class="input-layout">
      <label>Contact Number 1</label>
      <input v-model.number="vcnum1" type="number" />
    </div>
    <div class="input-layout">
      <label>Contact Number 2</label>
      <input v-model.number="vcnum2" type="number" />
    </div>
    <div class="input-layout">
      <label>Email ID</label>
      <input v-model="vemail" placeholder="Enter Email ID" />
    </div>
    <div class="input-layout">
      <label>GST Number</label>
      <input v-model="vgst" type="text" placeholder="Enter GST Number" />
    </div>
    <div class="input-layout">
      <label>Credit Terms </label>
      <select v-model="vcreditterm">
        <option disabled value="">Please select the credit terms</option>
        <option>Immediate Payment</option>
        <option>7 days</option>
        <option>30 days</option>
        <option>60 days</option>
        <option>90 days</option>
      </select>
    </div>
    <div>
      <button @click="addVendor" class="button btnadd">Add Vendor</button>
    </div>
  </div>
  <div class="displaysection">
    <form action="" class="gridbutton">
      <div>
        <input type="text" name="search" id="search" v-model="search" />
        <button>Search by Vendor Code</button> (or)
        <input type="text" name="search" id="search" v-model="search" />
        <button>Search by Vendor Name</button>
      </div>
    </form>

    <div class="table">
      <table id="vendorTable">
        <thead>
          <tr>
            <th>Vendor Code</th>
            <th>Vendor Name</th>
            <th>Vendor Address</th>
            <th>State</th>
            <th>Contact Person</th>
            <th>Designation</th>
            <th>Contact Num1</th>
            <th>Contact Num2</th>
            <th>Email ID</th>
            <th>GST Number</th>
            <th>Credit Terms</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(row, index) in rows" :key="index">
            <td>{{ row.vcode }}</td>
            <td>{{ row.vname }}</td>
            <td>{{ row.vaddress }}</td>
            <td>{{ row.vstate }}</td>
            <td>{{ row.vcontactperson }}</td>
            <td>{{ row.vdesig }}</td>
            <td>{{ row.vcnum1 }}</td>
            <td>{{ row.vcnum2 }}</td>
            <td>{{ row.vemail }}</td>
            <td>{{ row.vgst }}</td>
            <td>{{ row.vcreditterm }}</td>
            <link
              rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
            />
            <td>
              <button>
                <span class="glyphicon glyphicon-edit"></span>Edit
              </button>
              <button @click="deleteVendor(index)">
                <span class="glyphicon glyphicon-trash"></span> Delete
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>


<script>
export default {
  data() {
    return {
      rows: [
        {
          vcode: "VC001",
          vname: "ABC Pvt Ltd",
          vaddress: "Trivandrum",
          vstate: "Kerala",
          vcontactperson: "Mr.XXX",
          vdesig: "Manager",
          vcnum1: "9876543219",
          vcnum2: "0471224433",
          vemail: "abcmanager@gmail.com",
          vgst: "GSTIN1234567890123456",
          vcreditterm: "Immediately",
        },
        {
          vcode: "VC002",
          vname: "XYZ Pvt Ltd",
          vaddress: "Neyyatinkara",
          vstate: "Kerala",
          vcontactperson: "Mr.YYY",
          vdesig: "SalesMan",
          vcnum1: "8475859472",
          vcnum2: "",
          vemail: "xyz@gmail.com",
          vgst: "",
          vcreditterm: "30days",
        },
      ],
    };
  },
  methods: {
    addVendor() {
      this.rows.push({
        vcode: this.vcode,
        vname: this.vname,
        vaddress: this.vaddress,
        vstate: this.vstate,
        vcontactperson: this.vcontactperson,
        vdesig: this.vdesig,
        vcnum1: this.vcnum1,
        vcnum2: this.vcnum2,
        vemail: this.vemail,
        vgst: this.vgst,
        vcreditterm: this.vcreditterm,
      });
      this.clearForm();
    },
    clearForm() {
      this.vcode = "";
      this.vname = "";
      this.vaddress = "";
      this.vstate = "";
      this.vcontactperson = "";
      this.vdesig = "";
      this.vcnum1 = "";
      this.vcnum2 = "";
      this.vemail = "";
      this.vgst = "";
      this.vcreditterm = "";
    },
    deleteVendor(index) {
      this.rows.splice(index, 1);
    },
  },
};
</script>

<style scoped>
.list-view {
  display: grid;
  grid-template-columns: 1fr 1fr;
  /*background-color: tan;*/
  text-align: left;
  margin: 25px 20px 5px 20px;
}
.gridbutton {
  display: grid;
  grid-template-columns: 4fr 1fr;
  margin: 20px 10px 5px 10px;
}
.gridbutton input,
.gridbutton button {
  height: 30px;
  font-size: 18px;
}
.gridbutton input {
  width: 300px;
}
.gridbutton button {
  width: auto;
  cursor: pointer;
}

.button {
  border-radius: 30px;
  width: auto;
  height: 40px;
  text-transform: uppercase;
  border: 2px solid black;
  box-shadow: 4px 4px 4px black;
  font-size: 18px;
  font-weight: bold;
  cursor: pointer;
  /*margin-top: 25px;*/
}

.btnadd {
  margin-left: 25%;
}

.input-layout {
  display: flex;
  align-items: center;
  flex-direction: row;
  padding: 5px;
  margin: 0px 60px;
}
.input-layout label {
  margin-right: auto;
  font-size: 18px;
}
.input-layout input,
.input-layout select {
  width: 250px;
  height: 30px;
  font-size: 18px;
  border: 2px solid black;
  border-radius: 3px;
}

.input-layout textarea {
  width: 250px;
  height: 70px;
  font-size: 18px;
  border: 2px solid black;
  margin-left: 40px;
}
input[type="number"]::-webkit-outer-spin-button,
input[type="number"]::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
.displaysection {
  /*background-color: burlywood;*/
  margin: 10px;
  position: relative;
}
.table {
  width: fit-content;
  /*border-collapse: collapse;*/

  border: 2px solid #44475c;
  margin: 5px 5px 5px 5px;
}

.table th {
  /*text-transform: uppercase;*/
  text-align: center;
  background: #44475c;
  color: #fff;
  padding: 3px;
  min-width: 30px;
}

.table td {
  text-align: left;
  padding: 5px;
  border-right: 2px solid #7d82a8;
}

/*.table td:last-child {
  border-right: none;
}*/
.table tbody tr:nth-child(2n) td {
  background: #d4d8f9;
}
</style>
