<template>
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
  />
  <div class="list-view">
    <div class="input-layout">
      <label>Vendor Code </label>
      <input v-model="vendor.code" placeholder="Autogenerated Vendor Code" />
    </div>
    <div class="input-layout">
      <label>Vendor Name </label>
      <input v-model="vendor.name" placeholder="Enter Vendor Name" />
    </div>
    <div class="input-layout">
      <label>Address </label>
      <textarea v-model="vendor.address" placeholder="Address"></textarea>
    </div>
    <div class="input-layout">
      <label>State </label>
      <select v-model="vendor.state">
        <option disabled value="">Please select state</option>
        <option>Kerala</option>
        <option>Tamil Nadu</option>
      </select>
    </div>
    <div class="input-layout">
      <label>Contact Person</label>
      <input
        v-model="vendor.contactperson"
        placeholder="Enter Contact Person Name"
      />
    </div>
    <div class="input-layout">
      <label>Designation</label>
      <input
        v-model="vendor.desig"
        placeholder="Contact Person's Designation'"
      />
    </div>
    <div class="input-layout">
      <label>Contact Number 1</label>
      <input v-model.number="vendor.cnum1" type="number" />
    </div>
    <div class="input-layout">
      <label>Contact Number 2</label>
      <input v-model.number="vendor.cnum2" type="number" />
    </div>
    <div class="input-layout">
      <label>Email ID</label>
      <input v-model="vendor.email" placeholder="Enter Email ID" />
    </div>
    <div class="input-layout">
      <label>GST Number</label>
      <input v-model="vendor.gst" type="text" placeholder="Enter GST Number" />
    </div>
    <div class="input-layout">
      <label>Credit Terms </label>
      <select v-model="vendor.creditterm">
        <option disabled value="">Please select the credit terms</option>
        <option>Immediate Payment</option>
        <option>7 days</option>
        <option>30 days</option>
        <option>60 days</option>
        <option>90 days</option>
      </select>
    </div>
    <div>
      <button @click="addVendor()" class="button btnadd">Save Vendor</button>
    </div>
  </div>
  <div id="search">
    <div class="searchsection">
      <input
        type="text"
        name="searchvendorcode"
        id="searchvendorcode"
        v-model="searchcode"
        @keyup="searchVendorbyCode()"
        placeholder="Search by Code"
      />
      <i class="glyphicon glyphicon-search"></i>
      <!--p>Searching content : {{ searchcode }}</p-->

      <input
        type="text"
        name="searchvendorname"
        id="searchvendorname"
        v-model="searchname"
        @keyup="searchVendorbyName()"
        placeholder="Search by Name"
      />
      <i class="glyphicon glyphicon-search"></i>
      <!--p>Searching content : {{ searchname }}</p-->
    </div>
  </div>
  <div class="displaysection">
    <div class="table">
      <table id="vendorTable">
        <thead>
          <tr>
            <th>Vendor Code</th>
            <th>Vendor Name</th>
            <th>Vendor Address</th>
            <th>State</th>
            <th>Contact Person</th>
            <th>Designation</th>
            <th>Contact Num1</th>
            <th>Contact Num2</th>
            <th>Email ID</th>
            <th>GST Number</th>
            <th>Credit Terms</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(vendor, index) in rows" :key="index">
            <td>{{ vendor.code }}</td>
            <td>{{ vendor.name }}</td>
            <td>{{ vendor.address }}</td>
            <td>{{ vendor.state }}</td>
            <td>{{ vendor.contactperson }}</td>
            <td>{{ vendor.desig }}</td>
            <td>{{ vendor.cnum1 }}</td>
            <td>{{ vendor.cnum2 }}</td>
            <td>{{ vendor.email }}</td>
            <td>{{ vendor.gst }}</td>
            <td>{{ vendor.creditterm }}</td>

            <td>
              <button @click="editVendor(index)" class="iconbutton">
                <span class="glyphicon glyphicon-edit"></span>
              </button>
              <button @click="deleteVendor(index)" class="iconbutton">
                <span class="glyphicon glyphicon-trash"></span>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>


<script>
export default {
  data() {
    return {
      vendor: {},
      searchname: "",
      searchcode: "",

      initialdata: [
        {
          code: "VC001",
          name: "ABC Pvt Ltd",
          address: "Trivandrum",
          state: "Kerala",
          contactperson: "Mr.XXX",
          desig: "Manager",
          cnum1: "9876543219",
          cnum2: "0471224433",
          email: "abcmanager@gmail.com",
          gst: "GSTIN1234567890123456",
          creditterm: "Immediate Payment",
        },
        {
          code: "VC002",
          name: "XYZ Pvt Ltd",
          address: "Neyyatinkara",
          state: "Tamil Nadu",
          contactperson: "Mr.YYY",
          desig: "SalesMan",
          cnum1: "8475859472",
          cnum2: "",
          email: "xyz@gmail.com",
          gst: "",
          creditterm: "30 days",
        },
      ],
      rows: this.initialdata,
    };
  },

  methods: {
    addVendor() {
      this.rows.push(this.vendor);
      this.vendor = {};
      //this.rows[index] = JSON.parse(JSON.stringify(this.rows[index]));
    },

    editVendor(index) {
      this.vendor = JSON.parse(JSON.stringify(this.rows[index]));
      //this.vendor = this.rows[index];
    },

    deleteVendor(index) {
      var delconfirmation = confirm("Are you sure to delete this vendor ?");
      if (delconfirmation) {
        this.rows.splice(index, 1);
      }
    },
    searchVendorbyCode() {
      this.rows = this.initialdata.filter((vendor) =>
        vendor.code.toLowerCase().includes(this.searchcode.toLowerCase())
      );
    },
    searchVendorbyName() {
      this.rows = this.initialdata.filter((vendor) =>
        vendor.name.toLowerCase().includes(this.searchname.toLowerCase())
      );
    },
  },
  created() {
    this.searchVendorbyCode();
    this.searchVendorbyName();
  },
};
</script>

<style scoped>
.list-view {
  display: grid;
  grid-template-columns: 1fr 1fr;
  /*background-color: tan;*/
  text-align: left;
  margin: 25px 20px 5px 20px;
}
.gridbutton {
  display: grid;
  grid-template-columns: 4fr 1fr;
  margin: 20px 10px 5px 10px;
}
.gridbutton input,
.gridbutton button {
  height: 30px;
  font-size: 18px;
}
.gridbutton input {
  width: 300px;
}
.gridbutton button {
  width: auto;
  cursor: pointer;
}

.button {
  height: 35px;
  width: auto;
  border-radius: 30px;
  text-transform: uppercase;
  border: 2px solid black;
  box-shadow: 4px 4px 4px black;
  font-size: 18px;
  font-weight: bold;
  cursor: pointer;
  /*margin-top: 25px;*/
}
.iconbutton {
  width: auto;
  height: auto;
  border: none;
  background-color: transparent;
}

.btnadd {
  margin-left: 25%;
}

.input-layout {
  display: flex;
  align-items: center;
  flex-direction: row;
  padding: 5px;
  margin: 0px 60px;
}
.input-layout label {
  margin-right: auto;
  font-size: 18px;
}
.input-layout input,
.input-layout select {
  width: 250px;
  height: 30px;
  font-size: 18px;
  border: 2px solid black;
  border-radius: 3px;
}

.input-layout textarea {
  width: 250px;
  height: 70px;
  font-size: 18px;
  border: 2px solid black;
  margin-left: 40px;
}
input[type="number"]::-webkit-outer-spin-button,
input[type="number"]::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
.displaysection {
  /*background-color: burlywood;*/
  margin: 10px;
  position: relative;
}
.table {
  /*border-collapse: collapse;*/
  width: fit-content;
  border: 2px solid #44475c;
  margin: 5px 5px 5px 5px;
}

.table th {
  /*text-transform: uppercase;*/
  text-align: center;
  background: #44475c;
  color: #fff;
  padding: 3px;
  min-width: 40px;
}

.table td {
  text-align: left;
  padding: 5px;
  border-right: 2px solid #7d82a8;
  word-wrap: break-word;
  max-width: 140px;
}

/*.table td:last-child {
  border-right: none;
}*/
.table tbody tr:nth-child(2n) td {
  background: #d4d8f9;
}

.searchsection {
  display: grid;
  grid-template-columns: 1fr 0.1fr 1fr 0.1fr 5fr;
  margin: 35px 20px 10px;
}
.searchsection input,
.searchsection i {
  border-right-style: none;
  border-left-style: none;
  border-top-style: none;
  border-bottom-width: medium;
  border-bottom-color: black;
}
.searchsection i {
  margin-right: 35px;
}
</style>
